// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class BlockDodgerResources
{
        public const string achievement_power_up_collector = "CgkIxsmT_awEEAIQCA"; // <GPGSID>
        public const string achievement_generous_human_being = "CgkIxsmT_awEEAIQFg"; // <GPGSID>
        public const string achievement_ghosty_collector = "CgkIxsmT_awEEAIQEw"; // <GPGSID>
        public const string achievement_real_human_being_and_a_real_hero = "CgkIxsmT_awEEAIQGA"; // <GPGSID>
        public const string achievement_minime_novice = "CgkIxsmT_awEEAIQDA"; // <GPGSID>
        public const string achievement_minime_master = "CgkIxsmT_awEEAIQDg"; // <GPGSID>
        public const string achievement_timey_master = "CgkIxsmT_awEEAIQEQ"; // <GPGSID>
        public const string achievement_dodge_pro = "CgkIxsmT_awEEAIQHg"; // <GPGSID>
        public const string achievement_keep_going = "CgkIxsmT_awEEAIQGw"; // <GPGSID>
        public const string achievement_human_being = "CgkIxsmT_awEEAIQFQ"; // <GPGSID>
        public const string achievement_real_human_being = "CgkIxsmT_awEEAIQFw"; // <GPGSID>
        public const string achievement_dedicated_dodge_blocker = "CgkIxsmT_awEEAIQHQ"; // <GPGSID>
        public const string achievement_minime_collector = "CgkIxsmT_awEEAIQDQ"; // <GPGSID>
        public const string achievement_you_got_this = "CgkIxsmT_awEEAIQHA"; // <GPGSID>
        public const string achievement_dodge_master = "CgkIxsmT_awEEAIQIQ"; // <GPGSID>
        public const string achievement_dodge_legend = "CgkIxsmT_awEEAIQIg"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkIxsmT_awEEAIQAQ"; // <GPGSID>
        public const string achievement_advert_watcher = "CgkIxsmT_awEEAIQGQ"; // <GPGSID>
        public const string achievement_power_up_novice = "CgkIxsmT_awEEAIQBw"; // <GPGSID>
        public const string achievement_power_up_master = "CgkIxsmT_awEEAIQCQ"; // <GPGSID>
        public const string achievement_timey_collector = "CgkIxsmT_awEEAIQEA"; // <GPGSID>
        public const string achievement_ghosty_novice = "CgkIxsmT_awEEAIQEg"; // <GPGSID>
        public const string achievement_ghosty_master = "CgkIxsmT_awEEAIQFA"; // <GPGSID>
        public const string achievement_timey_novice = "CgkIxsmT_awEEAIQDw"; // <GPGSID>
        public const string achievement_do_not_give_up = "CgkIxsmT_awEEAIQGg"; // <GPGSID>
        public const string achievement_dodge_veteran = "CgkIxsmT_awEEAIQHw"; // <GPGSID>
        public const string achievement_dodge_expert = "CgkIxsmT_awEEAIQIA"; // <GPGSID>

}

